name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
      run: |
        echo $host >> secrets.txt
        echo $username >> secrets.txt
        echo $key >> secrets.txt
        echo $port >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
